blueprint:
  name: '[Notify] Notifications for AndroidTV'
  description: Fire a notification only if it is active by a binary_sensor
  domain: automation
  # source_url: https://github.com/home-assistant/core/blob/dev/homeassistant/components/template/blueprints/inverted_binary_sensor.yaml
  input:
    notify_action:
      name: "Notify Action"
      description: "Select the nfandroid notify service."
      selector:
        config_entry:
          integration: nfandroidtv
          # integration: mobile_app
          # integration: alexa_media

mode: restart


variables:
  input_notify_action: !input notify_action

triggers:
  - trigger: event
    event_type: notification_notify
    event_data:
      targets:
        device_screen: true

actions:
  - variables:
      notify_action: "notify.{{ config_entry_attr(input_notify_action, 'title') }}"
      message: "{{- message.split('|')|map('trim')|map('striptags')|join('<br>') -}}"
      title: "{{- title -}}"
      color: "{{- color | default('indigo') -}}"
      position: "{{- position | default('bottom-right') -}}"
      fontsize: "{{- fontsize | default('max') -}}"
      transparency: "{{- transparency | default(0) -}}%"
      duration: "{{- duration | default(5) | int -}}"
      interrupt: "{{- interrupt | default(False) | bool -}}"
      image_url: "{{- image_url | default(None) -}}"
      icon_url: >-
        {%- from 'emoji.jinja' import emoji_to_png -%}
        {%- if icon_url is not none -%}
          {{ icon_url }}
        {%- elif title is not none -%}
          {{ emoji_to_png(title) }}
        {%- else -%}  
          {{ None }}
        {%- endif -%}

  - condition: template
    value_template: "{{ target | select(\"in\", input_listen_targets) | list | count > 0 }}"

  - action: "{{ notify_action | default('notify.send_message') }}"
    data:
      message: "{{ message }}"
      title: "{{ title }}"
      data:
        color: "{{ color }}"
        position: "{{ position }}"
        fontsize: "{{ fontsize }}"
        transparency: "{{ transparency }}"
        duration: "{{ duration }}"
        interrupt: "{{ interrupt }}"
        image:
          url: "{{ image }}"
        icon:
          url: "{{ icon }}"
